Add LSP-leo package.
sublimelsp/repository pull request #51
Opened 2021-08-19 14:37 UTC by dev-sptg

Hello.
Leo is a functional, statically-typed programming language built for writing private applications.
https://leo-lang.org/
https://developer.aleo.org/developer/getting_started/overview

This package provides LSP features (diagnostics, completions, hovers, go-to definitions, semantic highlights) and also a theme for syntax token coloring.

2021-08-19 16:06 UTC, rwols commented
Thanks for adding a helper pacakge :) I have a few comments about the python side of things:

- Is a `threading.Timer` really necessary? Can we do without? It seems like we're spawning many `threading.Timers` and not cleaning them up?
- This file seems unnecessary: https://github.com/sublimelsp/LSP-leo/blob/master/leo.sublime-settings. can the file extensions be declared in the .tmLanguage file instead?
- Please don't ship a Preferences.sublime-settings file. This overrides global settings and is not what end-users usually expect.
- Please don't modify private variables: https://github.com/sublimelsp/LSP-leo/blob/master/plugin.py#L51
- As the bot mentions, adding a LICENSE.txt file will let me and others know whether I should put in effort to improve the package.

2021-08-20 10:03 UTC, dev-sptg commented
@rwols, I did fix all your comments in https://github.com/sublimelsp/LSP-leo/commit/b2d93304a96f5c4e53e9d0fe057746bc978161ff. Please check again.

2021-08-20 14:54 UTC, rwols commented
Sorry for the delay. I downloaded and set up Leo and tried LSP-leo.

- I really don't think the `setListener` function is necessary. You can use the file extension property in the tmLanguage file to let Sublime know what to associate to what kind of file. There is also a `firstLineMatch` property for tmLanguage files that let you associate the .in, .out and .result files to leoInput files as those files always seem to start with a certain comment.
- The server files are always copied to my cache folder, even if they're already present. Maybe that's an lsp_utils issue.
- Actual syntax highlighting could be improved, but I don't think that's necessary for now for release :)

2021-08-20 17:12 UTC, dev-sptg commented
> I really don't think the setListener function is necessary. You can use the file extension property in the tmLanguage file to let Sublime know what to associate to what kind of file. There is also a firstLineMatch property for tmLanguage files that let you associate the .in, .out and .result files to leoInput files as those files always seem to start with a certain comment.

Pushed commit into https://github.com/sublimelsp/LSP-leo/commit/f982401ab0a7bf3a6b70b814e06a3bd4b82907f7

> Actual syntax highlighting could be improved, but I don't think that's necessary for now for release :) EDIT: Note that this is the scope guide for Sublime. Scopes between VSCode and Sublime are diverging. But again, I don't think it's necessary to get all into scopes for a release.

I know about this issue. I will update scope names according to guide in next releases.

2021-08-21 13:41 UTC, rwols requested changes
Almost there.

2021-08-21 13:41 UTC, rwols commented on repository.json
> +			"readme": "https://raw.githubusercontent.com/sublimelsp/LSP-leo/master/README.md",
The `readme` is auto-deduced from the `details`, so can be omitted here.

2021-08-21 13:41 UTC, rwols commented on repository.json
> +			"description": "A leo language features extension.",
The `description` is auto-deduced from the `details`, so can be omitted.

2021-08-21 13:41 UTC, rwols commented on repository.json
> +			]
I'm not sure why this json object isn't sitting between the other json objects in the json array. Maybe it works? I don't know. Just put it between the others (in alphabetical order).

2021-08-21 13:41 UTC, rwols commented on repository.json
> +}
nitpick: missing newline

2021-08-21 14:47 UTC, rchl commented
>     * The server files are always copied to my cache folder, even if they're already present. Maybe that's an lsp_utils issue.

It looks like it. Sort of. Because this server doesn't include any dependencies, the `node_modules` directory is not created on running `npm install`. Due to that, `lsp_utils` thinks that the server was not installed yet.

Not sure how would we fix that.

2021-08-24 05:43 UTC, dev-sptg commented
@rwols, I pushed fixes according to the latest recommendations.

2021-08-24 05:53 UTC, dev-sptg commented
> LICENSE

@rwols, I don't know why this warning appears. I have a LICENSE file at the root of the repository.

2021-08-24 06:12 UTC, rchl commented
The bot is checking the latest tagged version, not the master branch.

2021-08-24 15:25 UTC, rwols approved these changes
:ship:

2021-08-24 15:25 UTC, merged